 document.writeln('  <ul>');
 document.writeln('                	<li class="loginbackground fontcolor" style="height:26px;line-height:26px;">03-13 星期四</li>');
 document.writeln('                    <li class="fontcolor2" style="line-height:25px;height:25px;border-left:1px solid #dddfe1;border-right:1px solid #dddfe1;border-bottom:1px dashed #dddfe1; font-size:16px">08:30:01</li>');
 document.writeln('                    <li class="fontcolor2" style="height:35px;line-height:17px;border-left:1px solid #dddfe1;border-right:1px solid #dddfe1;border-bottom:1px solid #dddfe1;border-right:1px solid #dddfe1;">');
document.writeln('                         <p>甲午年 三月初九</p>');
document.writeln('                         <p>丁卯月 壬寅日</p></li>');
document.writeln('                 </ul>');