package org.ytgs.security.model;

import org.springframework.stereotype.Component;

// Generated 2011-3-23 11:09:37 by Hibernate Tools 3.2.2.GA

/**
 * PubRolesAuthorities generated by hbm2java
 */
@SuppressWarnings("serial")
@Component
public class SysRolesAuthorities implements java.io.Serializable {

	private long id;
	private SysAuthorities sysAuthorities;
	private SysRoles sysRoles;
    private String authorityDesc;
	public String getAuthorityDesc() {
		return authorityDesc;
	}

	public void setAuthorityDesc(String authorityDesc) {
		this.authorityDesc = authorityDesc;
	}

	private String roleId;
	
	private String authorityId;
	
	private String enabled;

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getAuthorityId() {
		return authorityId;
	}

	public void setAuthorityId(String authorityId) {
		this.authorityId = authorityId;
	}

	public SysRolesAuthorities() {
	}

	public SysRolesAuthorities(long id) {
		this.id = id;
	}

	public SysRolesAuthorities(long id, SysAuthorities sysAuthorities,
			SysRoles sysRoles, String enabled) {
		this.id = id;
		this.sysAuthorities = sysAuthorities;
		this.sysRoles = sysRoles;
		this.enabled = enabled;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public SysAuthorities getSysAuthorities() {
		return this.sysAuthorities;
	}

	public void setSysAuthorities(SysAuthorities sysAuthorities) {
		this.sysAuthorities = sysAuthorities;
	}

	public SysRoles getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(SysRoles sysRoles) {
		this.sysRoles = sysRoles;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}
	
//	public String getRoleId(){
//		return roleId;
//	}
//	
//	public void setRoleId( String roleId ){
//		this.roleId = roleId;
//	}
//	
//	public String getAuthorityId(){
//		return authorityId;
//	}
//	
//	public void setAuthorityId( String authorityId ){
//		this.authorityId = authorityId;
//	}

}
